test_that("t_mcSeason() works", {
  expect_identical(t_mcSeason(1, 1), 1)
  expect_identical(t_mcSeason(2, 29), 1)
  expect_identical(t_mcSeason(5, 31), 1)
  expect_identical(t_mcSeason(6, 1), 1.5)
  expect_identical(t_mcSeason(6, 15), 1.5)
  expect_identical(t_mcSeason(6, 16), 2)
  expect_identical(t_mcSeason(8, 31), 2)
  expect_identical(t_mcSeason(9, 1), 3)
  expect_error(t_mcSeason(0, 0))
  expect_error(t_mcSeason(0, 1))
  expect_error(t_mcSeason(1, 0))
  expect_error(t_mcSeason(2, 30))
  expect_error(t_mcSeason(13, 1))
  expect_error(t_mcSeason(1, 32))
  expect_error(t_mcSeason(1.5, 1))
  expect_error(t_mcSeason(1, 1.5))
  expect_error(t_mcSeason("", ""))
  expect_error(t_mcSeason(NA, NA))
  expect_error(t_mcSeason(NULL, NULL))
})

test_that("t_mcF() works", {
  expect_identical(t_mcF(80), 22.16)
  expect_identical(t_mcF(90), 10.83)
  expect_identical(t_mcF(91.5), 9.26)
  expect_identical(t_mcF(99), 1.86)
  expect_error(t_mcF(79))
  expect_error(t_mcF(100))
  expect_error(t_mcF(""))
  expect_error(t_mcF(NA))
  expect_error(t_mcF(NULL))
})

test_that("t_mcsa() works", {
  expect_identical(t_mcsa(80, 20, 1, 3, "s"), 23.45)
  expect_identical(t_mcsa(84, 30, 1, 3, "p"), 16.33)
  expect_identical(t_mcsa(89, 40, 2, 2, "p"), 12.3)
  expect_identical(t_mcsa(92, 60, 2, 1, "p"), 7.5)
  expect_error(t_mcsa(79, 60, 2, 1, "p"))
  expect_error(t_mcsa(100, 60, 2, 1, "p"))
  expect_error(t_mcsa(92, 4, 2, 1, "p"))
  expect_error(t_mcsa(92, 251, 2, 1, "p"))
  expect_error(t_mcsa(92, 60, 0, 1, "p"))
  expect_error(t_mcsa(92, 60, 1.6, 1, "p"))
  expect_error(t_mcsa(92, 60, 4, 1, "p"))
  expect_error(t_mcsa(92, 60, 2, 0, "p"))
  expect_error(t_mcsa(92, 60, 2, 1.6, "p"))
  expect_error(t_mcsa(92, 60, 2, 4, "p"))
  expect_error(t_mcsa(92, 60, 2, 1, 1))
  expect_error(t_mcsa(92, 60, 2, 1, "douglas fir"))
  expect_error(t_mcsa(NULL, 60, 2, 1, "p"))
  expect_error(t_mcsa(92, NULL, 2, 1, "p"))
  expect_error(t_mcsa(92, 60, NULL, 1, "p"))
  expect_error(t_mcsa(92, 60, 2, NULL, "p"))
  expect_error(t_mcsa(92, 60, 2, 1, NULL))
  expect_error(t_mcsa(NA, 60, 2, 1, "p"))
  expect_error(t_mcsa(92, NA, 2, 1, "p"))
  expect_error(t_mcsa(92, 60, NA, 1, "p"))
  expect_error(t_mcsa(92, 60, 2, NA, "p"))
  expect_error(t_mcsa(92, 60, 2, 1, NA))
  expect_error(t_mcsa("", 60, 2, 1, "p"))
  expect_error(t_mcsa(92, "", 2, 1, "p"))
  expect_error(t_mcsa(92, 60, "", 1, "p"))
  expect_error(t_mcsa(92, 60, 2, "", "p"))
  expect_error(t_mcsa(92, 60, 2, 1, ""))
})

test_that("t_pCFO() works", {
  expect_identical(t_pCFO(mcsa = 10, FSG = 6, SFC = 2, ws = 11), 0.18)
  expect_identical(t_pCFO(mcsa = 9, FSG = 6, SFC = 2, ws = 12), 0.51)
  expect_identical(t_pCFO(mcsa = 8, FSG = 6, SFC = 2, ws = 13), 0.86)
  expect_identical(t_pCFO(mcF = 10, FSG = 6, SFC = 2, ws = 11), 0.25)
  expect_identical(t_pCFO(mcF = 9, FSG = 6, SFC = 2, ws = 12), 0.6)
  expect_identical(t_pCFO(mcF = 8, FSG = 6, SFC = 2, ws = 13), 0.88)
  expect_identical(t_pCFO(mcsa = 8, mcF = 8, FSG = 6, SFC = 2, ws = 13), 0.88)
  expect_error(t_pCFO(mcsa = 2.9, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 20.1, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcF = 2.9, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcF = 20.1, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 0.4, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 20.1, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = 0, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = 6.1, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = 2, ws = -1))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = 2, ws = 61))
  expect_error(t_pCFO(mcsa = NULL, mcF = NULL, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = NULL, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = NULL, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = 2, ws = NULL))
  expect_error(t_pCFO(mcsa = NA, mcF = NA, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = NA, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = NA, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = 2, ws = NA))
  expect_error(t_pCFO(mcsa = "", mcF = "", FSG = 6, SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = "", SFC = 2, ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = "", ws = 13))
  expect_error(t_pCFO(mcsa = 8, FSG = 6, SFC = 2, ws = ""))
})

test_that("t_FT() works", {
  expect_identical(t_FT(mcsa = 9, FSG = 6, SFC = 2, CBD = 0.1, ws = 11), "S")
  expect_identical(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = 11), "PC")
  expect_identical(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.2, ws = 11), "AC")
  expect_identical(t_FT(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = 0.6), "S")
  expect_error(t_FT(mcsa = 2.9, FSG = 6, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 20.1, FSG = 6, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcF = 2.9, FSG = 6, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcF = 20.1, FSG = 6, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 0.4, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 20.1, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 0, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 6.1, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.9, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = -1))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = 61))
  expect_error(t_FT(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = -1))
  expect_error(t_FT(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = 1.1))
  expect_error(t_FT(mcsa = NULL, mcF = NULL, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = NULL, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = NULL, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = NULL, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = NULL))
  expect_error(t_FT(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = NULL))
  expect_error(t_FT(mcsa = NA, mcF = NA, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = NA, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = NA, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = NA, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = NA))
  expect_error(t_FT(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = NA))
  expect_error(t_FT(mcsa = "", mcF = "", FSG = 6, SFC = 2, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = "", SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = "", CBD = 0.1, ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = "", ws = 13))
  expect_error(t_FT(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = ""))
  expect_error(t_FT(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = ""))
})

test_that("t_ROS() works", {
  expect_snapshot(t_ROS(mcsa = 9, FSG = 6, SFC = 2, CBD = 0.1, ws = 11))
  expect_snapshot(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = 11))
  expect_snapshot(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.2, ws = 11))
  expect_snapshot(t_ROS(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = 0.6))
  expect_error(t_ROS(mcsa = 2.9, FSG = 6, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 20.1, FSG = 6, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcF = 2.9, FSG = 6, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcF = 20.1, FSG = 6, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 0.4, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 20.1, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 0, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 6.1, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.9, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = -1))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = 61))
  expect_error(t_ROS(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = -1))
  expect_error(t_ROS(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = 1.1))
  expect_error(t_ROS(mcsa = NULL, mcF = NULL, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = NULL, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = NULL, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = NULL, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = NULL))
  expect_error(t_ROS(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = NULL))
  expect_error(t_ROS(mcsa = NA, mcF = NA, FSG = 6, SFC = 2, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = NA, SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = NA, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = NA, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = NA))
  expect_error(t_ROS(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = NA))
  expect_error(t_ROS(mcsa = "", mcF = "", FSG = 6, SFC = 2, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = "", SFC = 2, CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = "", CBD = 0.1, ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = "", ws = 13))
  expect_error(t_ROS(mcsa = 8, FSG = 6, SFC = 2, CBD = 0.1, ws = ""))
  expect_error(t_ROS(mcsa = 8, CBD = 0.2, ws = 11, CF_thresh = ""))
})

test_that("t_FMC() works", {
  expect_identical(t_FMC(), list(FMC = 120))
  expect_error(t_FMC(LAT = 41))
  expect_error(t_FMC(LAT = 71))
  expect_error(t_FMC(LONG = 52))
  expect_error(t_FMC(LONG = 142))
  expect_error(t_FMC(ELV = -1))
  expect_error(t_FMC(ELV = 2501))
  expect_error(t_FMC(Dj = -1))
  expect_error(t_FMC(Dj = 367))
})

test_that("t_SFC_FBP() works", {
  expect_snapshot(t_SFC_FBP())
  expect_error(t_SFC_FBP(BUI = -1))
  expect_error(t_SFC_FBP(BUI = 201))
  expect_error(t_SFC_FBP(FFMC = 79))
  expect_error(t_SFC_FBP(FFMC = 101))
  expect_error(t_SFC_FBP(PC = -1))
  expect_error(t_SFC_FBP(PC = 101))
})

test_that("t_SFC_deGroot() works", {
  expect_identical(
    t_SFC_deGroot(),
    list("Forest Floor Fuel Consumption" = 1.65, "SFC" = 1.95)
  )
  expect_error(t_SFC_FBP(BUI = -1))
  expect_error(t_SFC_FBP(BUI = 201))
  expect_error(t_SFC_FBP(FFL = 0.5))
  expect_error(t_SFC_FBP(FFL = 5.5))
  expect_error(t_SFC_FBP(FWFL = -1))
  expect_error(t_SFC_FBP(FWFL = 2.5))
})

test_that("ladder_standing_dead() works", {
  expect_identical(
    ladder_standing_dead(),
    list(
      "LFSG [m]" = 4,
      "Scaled SFC contribution, small snags [kg/m^2]" = 1.14
    )
  )
  expect_error(ladder_standing_dead(consumption = 0))
  expect_error(ladder_standing_dead(consumption = 11))
  expect_error(ladder_standing_dead(cl = 0))
  expect_error(ladder_standing_dead(cl = 16))
  expect_error(ladder_standing_dead(FSG = 0))
  expect_error(ladder_standing_dead(FSG = 21))
})

test_that("ladder_midstory_saplings() works", {
  expect_snapshot(ladder_midstory_saplings())
})
